### ISSUE TITLE
C style / JS style sexy comments

### ISSUE THREAD

**Issue by bryankennedy** [scrooloose/nerdcommenter#159] opened 2014-09-18 11:47 UTC
Right now, if I start with a block of text like this:
```
Comment headline

Iriure feugait amet, autem aliquip et ut, accumsan ea te duis facilisi illum dolore
```
and then apply the NERDComSexyComments command it ends up looking like this:
```
/*
 *Comment headline
 *
 *Iriure feugait amet, autem aliquip et ut, accumsan ea te duis facilisi illum dolore
 */
```

I'd like to figure out a way to wrap this text in [C++ Style comment blocks](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Comments#Comments) comment block. So that the text would look like this.
```
/**
 * Comment headline
 *
 * Iriure feugait amet, autem aliquip et ut, accumsan ea te duis facilisi illum dolore
 */
```
Notice the two leading asterisks and the spaces after the next line asterisks that aren't immediately followed by a line break.

Would you be amenable to this change for NERDComSexyComments, or should this get broken out into another command?

**Comment by jasonseney** [comment] 2015-06-03 19:19
+1 - This matches standard PHP commenting as well.

**Comment by alerque** [comment] 2016-05-24 07:03
This seems to be a duplicate of #125. I've suggested a possible solution there. If that isn't enough, please drop a comment there about what needs improving and I'll re-open it for discussion there. Thanks for the report!

**Closed by alerque** 2016-05-24 07:03 UTC
