### ISSUE TITLE
`let` syntax not loading alternate comment delimiters.

### ISSUE THREAD

**Issue by pharpend** [scrooloose/nerdcommenter#133] opened 2013-10-11 00:25 UTC
Whether or not I add 

```vim
let NERD_haskell_alt_style=1
```
NERD still uses the  ugly`{- ... -}` comment style by default.  I can still use `\ca` to change to the standard `-- ...` comment style.

I have tried to use the alternate style by default in Java, Haskell, and SCSS. No matter what language, NERD still uses the original style.

Vim 7.4 on Manjaro Linux. Installed most recent NERD Commenter using Pathogen.

**EDIT**

Tried reinstall (both ways) to no avail.

The variable isn't getting reset. The output of `:echo NERD_java_alt_style` is `1` before and after I load a Java file. The variable doesn't change after typing `\ca`. This leads me to believe the commenter is ignoring the variable.

**Comment by alerque** [comment] 2016-05-24 06:38
This seems to be a duplicate of #33, and no this does not seem to be implemented. Any volunteers?

**Closed by alerque** 2016-05-24 06:38 UTC
