### ISSUE TITLE
Installation with vim-plug

### ISSUE THREAD

**Issue by jleclanche** [scrooloose/nerdcommenter#233] opened 2016-03-11 10:10 UTC
I'm using [vim-plug](https://github.com/junegunn/vim-plug) with neovim, added `Plug 'scrooloose/nerdcommenter'` and ran `:PlugInstall`. NERD_commenter.vim is in the runtime path but nothing is bound. `:echo hasmapto('<plug>NERDCommenterInsert')` is `0`.

Any idea?

**Comment by alerque** [comment] 2016-05-24 08:12
I'm using vim-plug myself and have never seen this issue. Are you still seeing this in the current version (and having restarated vim)? Are you sure you know what your `<leader>` is?

**Comment by jleclanche** [comment] 2016-05-24 12:01
I ended up switching to tcomment. But I remember having problems with `set paste` in my options, I'd bet it's the same issue here.

**Comment by alerque** [comment] 2016-05-24 13:01
Thanks for the feedback @jleclanche, but I'm not quite sure I follow. What would `set paste` have to do with this? Are you saying the `Plug 'scrooloose/nerdcommenter'` line didn't actually get entered correctly? In that case this wouldn't be a problem with this plugin, no?

**Comment by jleclanche** [comment] 2016-05-24 13:08
No, it surprised me as well but "set paste" conflicts with a couple of comment plugins I tried, including tcomment and I had to remove it.

Could be the same issue there. No idea, just a thought!

**Comment by alerque** [comment] 2016-05-24 13:13
I don't normally have `set paste` turned on (except briefly when I paste!) but I just tried it and it doesn't seem to impair NERDCommenter at all. I'm going to close this for now since it seems unreproducible. It's possible there  was some problem at the time of your report that has since been solved. If you have trouble again just poke back here.

@saro Was your thumbs up an indication that you had the same problem? If so please comment here with details because I can't reproduce this. Thanks.

**Closed by alerque** 2016-05-24 13:13 UTC
Labels: needs info
