### ISSUE TITLE
How to enable alternative delimiters by default?

### ISSUE THREAD

**Issue by fhaust** [scrooloose/nerdcommenter#211] opened 2015-10-18 12:17 UTC
Specifically for Haskell there are two types of delimiters. The default `{- comment -}` and an alternative `-- comment`. I prefer the later so I switch to the alternate set using `NERDComAltDelim` often. Is there a way to have the alternative comment style enabled by default?

**Comment by vivekimsit** [comment] 2016-01-18 05:58
+1

**Comment by alerque** [comment] 2016-05-24 07:54
A way to do this was suggested (and document) but not actually implemented. See #33 for details. I'm closing this as a duplicate of that as whatever solution is brought for that will answer this issue as well. Thanks for the report.

**Closed by alerque** 2016-05-24 07:54 UTC

**Comment by DusanDimitric** [comment] 2019-04-14 13:49
Hello, this would be really nice to have since I haven't found a way to do this yet. It would be nice if it would be language-independent.
