### ISSUE TITLE
NERD_<filetype>_alt_style doesn't work

### ISSUE THREAD

**Issue by Wyatts** [scrooloose/nerdcommenter#145] opened 2014-03-13 14:15 UTC
It's documented but, from what I can tell of the source, it's not even implemented.

**Comment by alerque** [comment] 2016-05-24 06:54
This seems to be a duplicate of #33. I'll review the PR as soon as I can get to it. I've only just been added as a maintainer and am working through the issue backlog.

**Closed** 2016-05-24 06:54 UTC
