### ISSUE TITLE
GraphQL Comment Support

### ISSUE THREAD

**Issue by redreceipt** [scrooloose/nerdcommenter#391] opened 2019-08-07 14:15 UTC
GraphQL string literals should comment using `#`, currently it drops in a comment from the parent language (JS in my example case)

![Kapture 2019-08-07 at 10 15 43](https://user-images.githubusercontent.com/2659478/62630113-5773ff80-b8fc-11e9-8850-af1a78007ebc.gif)

**Comment by alerque** [comment] 2019-08-07 14:20
Thanks for reporting the issue, however this is a duplicate of issue #17. We'd happy to accept a contribution from anybody that resolves the issue of embedded languages having different syntax that their surrounding parents, but it's not an easy one to solve. For now probably the best you can do is setup a primary and alternate comment syntax to your liking and a really easy to type map to switch between them.

**Closed by alerque** 2019-08-07 14:20 UTC
Labels: duplicate
